a + b + c = 12

9*a + 3*b + c = 54

a - b + c = 2

In [1]:
import numpy as np

In [2]:
A = np.array([[1,1,1],[9,3,1],[1,-1,1]])

In [3]:
A

array([[ 1,  1,  1],
       [ 9,  3,  1],
       [ 1, -1,  1]])

In [4]:
b = np.array([12,54,2])

In [5]:
b

array([12, 54,  2])

In [6]:
results = np.linalg.solve(A,b)
results

array([4., 5., 3.])

Answer: y = 4x^2 + 5x + 3