In [12]:
import numpy as np

0.05x + 0.07y + 0z = 2250

0.05x + 0y + 0.06z = 1400

x + y + z = 50000

In [13]:
A = np.array([[0.05, 0.07, 0], [0.05, 0, 0.06], [1, 1, 1]])

In [14]:
A

array([[0.05, 0.07, 0.  ],
       [0.05, 0.  , 0.06],
       [1.  , 1.  , 1.  ]])

In [15]:
b = np.array([2250, 1400, 50000], dtype=float)

In [16]:
b

array([ 2250.,  1400., 50000.])

In [17]:
np.linalg.solve(A,b)

array([10000., 25000., 15000.])