Пусть x1 = 1/a^2; x2 = 1/b^2; x3 = 1/c^2; тогда составим систему линенйных уравнений, подставив значения координат точек:

3*x1 + 0*x2 + 3*x3 = 1

6*x1 + 0.25*x2 + 0*x3 = 1

1*x1 + 0.33*x2 + 1*x3 = 1

In [1]:
import numpy as np

In [2]:
A = np.array([[3,0,3],[6,0.25,0],[1,0.33,1]])

In [3]:
A

array([[3.  , 0.  , 3.  ],
       [6.  , 0.25, 0.  ],
       [1.  , 0.33, 1.  ]])

In [4]:
b = np.array([1,1,1])

In [5]:
b

array([1, 1, 1])

In [7]:
soln = np.linalg.solve(A,b)

In [8]:
soln

array([0.08249158, 2.02020202, 0.25084175])

Найдем значения a2, b2, c2 как a = 1/x1 и т.д.

In [9]:
a2 = 1 / soln[0]
b2 = 1 / soln[1]
c2 = 1 / soln[2]

In [10]:
a2, b2, c2

(12.122448979591837, 0.495, 3.9865771812080535)